#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# checks if branch has something pending
function parse_git_dirty() {
  git diff --quiet --ignore-submodules HEAD 2>/dev/null; [ $? -eq 1 ] && echo "*"
}


# gets the current git branch
function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

GIT_BRANCH=$(parse_git_branch)
BRANCH_NAME="staging"

if [ $GIT_BRANCH == $BRANCH_NAME ]; then
  read -p "Do you wish to install this program?" yn
  # case $yn in
  #   [Yy]* ) 
  #       npx standard-version
  #       rm changelog.html 
  #       cp -v changelog.md changelog.html
  #       echo "<script src="https://rawcdn.githack.com/oscarmorrison/md-page/master/md-page.js"></script><noscript>"|cat - changelog.html > /tmp/out && mv /tmp/out changelog.html
  #       ;;
  #   [Nn]* ) exit;;
  #  esac
 
fi    

