#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# checks if branch has something pending
function parse_git_dirty() {
  git diff --quiet --ignore-submodules HEAD 2>/dev/null; [ $? -eq 1 ] && echo "*"
}


# gets the current git branch
function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

GIT_BRANCH=$(parse_git_branch)

if [$GIT_BRANCH == "staging"]; then
    echo 'on STaging'
else
    echo 'not on staging'
fi    
