name: generate changelog
on: 
  push: 
   branches:
     - "staging"
jobs: 
  generate: 
    runs-on: macos-latest
    steps: 
      - name: checkout branch
        uses: actions/checkout@v2
        with:
          ref: 'staging'
          persist-credentials: false
      - name: Install git-chglog
        run: |
          brew tap git-chglog/git-chglog
          brew install git-chglog
      - name: Generate Changelog
        run: git-chglog -o CHANGELOG.md
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}  
          tags: true

