name: Build and release
on: 
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: nuuday/github-changelog-action@v1.0.0
        with:
          next_version: "1.0.0"

