name: generate changelog

on: 
  push: 
   branches:
     - "staging"

jobs: 
  generate: 
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: 'staging'
      - uses: actions/setup-node@v1
      - run: git branch
      - run: npx standard-version
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: generated Changelog
          skip_dirty_check: true 
